package cfg

import (
	rcfg "github.com/kalo-build/morphe-go/pkg/registry/cfg"
)

// CompileConfig holds all configuration for the compilation pipeline.
type CompileConfig struct {
	rcfg.MorpheLoadRegistryConfig

	// HandlersConfig configures generated handler output.
	HandlersConfig HandlersConfig

	// RepoConfig references the repository interface package (generated separately by plugin-morpherepo-go).
	RepoConfig RepoConfig

	// ModelsConfig references the existing models package.
	ModelsConfig ModelsConfig

	// StructuresConfig references the structures (DTO) package.
	StructuresConfig StructuresConfig

	// ExcludeModels lists model names to skip during generation.
	ExcludeModels []string

	// OutputDirPath is the base directory for generated output.
	OutputDirPath string

	// StructOutputDirPath is the directory where .str DTO files are written
	// (typically back to the morphe registry structures directory).
	StructOutputDirPath string
}

// HandlersConfig configures the generated handler package.
type HandlersConfig struct {
	// PackagePath is the full Go import path (e.g., "github.com/org/app/internal/generated/handlers").
	PackagePath string

	// PackageName is the short package name (e.g., "handlers"). Derived from PackagePath if empty.
	PackageName string
}

// RepoConfig references the repository interface package that handlers import.
type RepoConfig struct {
	// PackagePath is the full Go import path (e.g., "github.com/org/app/internal/generated/repo").
	PackagePath string

	// PackageName is the short package name (e.g., "repo"). Derived from PackagePath if empty.
	PackageName string
}

// ModelsConfig references the existing models package generated by plugin-morphe-go-struct.
type ModelsConfig struct {
	// PackagePath is the full Go import path (e.g., "github.com/org/app/internal/types/models").
	PackagePath string

	// PackageName is the short package name (e.g., "models"). Derived from PackagePath if empty.
	PackageName string
}

// StructuresConfig references the structures (DTO) package compiled by plugin-morphe-go-struct.
type StructuresConfig struct {
	// PackagePath is the full Go import path (e.g., "github.com/org/app/internal/types/structures").
	PackagePath string

	// PackageName is the short package name (e.g., "structures"). Derived from PackagePath if empty.
	PackageName string
}

// PackageNameFromPath extracts the last segment of a Go package path.
func PackageNameFromPath(pkgPath string) string {
	for i := len(pkgPath) - 1; i >= 0; i-- {
		if pkgPath[i] == '/' {
			return pkgPath[i+1:]
		}
	}
	return pkgPath
}

// Resolve fills in derived fields (package names from paths).
func (c *CompileConfig) Resolve() {
	if c.HandlersConfig.PackageName == "" {
		c.HandlersConfig.PackageName = PackageNameFromPath(c.HandlersConfig.PackagePath)
	}
	if c.RepoConfig.PackageName == "" {
		c.RepoConfig.PackageName = PackageNameFromPath(c.RepoConfig.PackagePath)
	}
	if c.ModelsConfig.PackageName == "" {
		c.ModelsConfig.PackageName = PackageNameFromPath(c.ModelsConfig.PackagePath)
	}
	if c.StructuresConfig.PackageName == "" {
		c.StructuresConfig.PackageName = PackageNameFromPath(c.StructuresConfig.PackagePath)
	}
}
